// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: serverRPC.proto

#include "serverRPC.pb.h"
#include "serverRPC.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ser {

static const char* serverRPC_method_names[] = {
  "/ser.serverRPC/isLeader",
  "/ser.serverRPC/execute",
};

std::unique_ptr< serverRPC::Stub> serverRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< serverRPC::Stub> stub(new serverRPC::Stub(channel, options));
  return stub;
}

serverRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_isLeader_(serverRPC_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_execute_(serverRPC_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status serverRPC::Stub::isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::ser::isLeaderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ser::isLeaderRequest, ::ser::isLeaderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_isLeader_, context, request, response);
}

void serverRPC::Stub::async::isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ser::isLeaderRequest, ::ser::isLeaderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_isLeader_, context, request, response, std::move(f));
}

void serverRPC::Stub::async::isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_isLeader_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>* serverRPC::Stub::PrepareAsyncisLeaderRaw(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ser::isLeaderResponse, ::ser::isLeaderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_isLeader_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>* serverRPC::Stub::AsyncisLeaderRaw(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncisLeaderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status serverRPC::Stub::execute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::ser::executeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ser::executeRequest, ::ser::executeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_execute_, context, request, response);
}

void serverRPC::Stub::async::execute(::grpc::ClientContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ser::executeRequest, ::ser::executeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_execute_, context, request, response, std::move(f));
}

void serverRPC::Stub::async::execute(::grpc::ClientContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_execute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ser::executeResponse>* serverRPC::Stub::PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ser::executeResponse, ::ser::executeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_execute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ser::executeResponse>* serverRPC::Stub::AsyncexecuteRaw(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncexecuteRaw(context, request, cq);
  result->StartCall();
  return result;
}

serverRPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      serverRPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< serverRPC::Service, ::ser::isLeaderRequest, ::ser::isLeaderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](serverRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ser::isLeaderRequest* req,
             ::ser::isLeaderResponse* resp) {
               return service->isLeader(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      serverRPC_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< serverRPC::Service, ::ser::executeRequest, ::ser::executeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](serverRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ser::executeRequest* req,
             ::ser::executeResponse* resp) {
               return service->execute(ctx, req, resp);
             }, this)));
}

serverRPC::Service::~Service() {
}

::grpc::Status serverRPC::Service::isLeader(::grpc::ServerContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status serverRPC::Service::execute(::grpc::ServerContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ser

