// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft_rpc.proto

#include "raft_rpc.pb.h"
#include "raft_rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace raft {

static const char* RaftRPC_method_names[] = {
  "/raft.RaftRPC/OnHeartBeat",
  "/raft.RaftRPC/OnRequestVote",
};

std::unique_ptr< RaftRPC::Stub> RaftRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftRPC::Stub> stub(new RaftRPC::Stub(channel, options));
  return stub;
}

RaftRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OnHeartBeat_(RaftRPC_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OnRequestVote_(RaftRPC_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RaftRPC::Stub::OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::raft::HeartBeatReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft::HeartBeatRequest, ::raft::HeartBeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OnHeartBeat_, context, request, response);
}

void RaftRPC::Stub::async::OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft::HeartBeatRequest, ::raft::HeartBeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnHeartBeat_, context, request, response, std::move(f));
}

void RaftRPC::Stub::async::OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnHeartBeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>* RaftRPC::Stub::PrepareAsyncOnHeartBeatRaw(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft::HeartBeatReply, ::raft::HeartBeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OnHeartBeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>* RaftRPC::Stub::AsyncOnHeartBeatRaw(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOnHeartBeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RaftRPC::Stub::OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::raft::VoteReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::raft::VoteRequest, ::raft::VoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OnRequestVote_, context, request, response);
}

void RaftRPC::Stub::async::OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::raft::VoteRequest, ::raft::VoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnRequestVote_, context, request, response, std::move(f));
}

void RaftRPC::Stub::async::OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnRequestVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raft::VoteReply>* RaftRPC::Stub::PrepareAsyncOnRequestVoteRaw(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::raft::VoteReply, ::raft::VoteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OnRequestVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::raft::VoteReply>* RaftRPC::Stub::AsyncOnRequestVoteRaw(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOnRequestVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

RaftRPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftRPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftRPC::Service, ::raft::HeartBeatRequest, ::raft::HeartBeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft::HeartBeatRequest* req,
             ::raft::HeartBeatReply* resp) {
               return service->OnHeartBeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftRPC_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftRPC::Service, ::raft::VoteRequest, ::raft::VoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftRPC::Service* service,
             ::grpc::ServerContext* ctx,
             const ::raft::VoteRequest* req,
             ::raft::VoteReply* resp) {
               return service->OnRequestVote(ctx, req, resp);
             }, this)));
}

RaftRPC::Service::~Service() {
}

::grpc::Status RaftRPC::Service::OnHeartBeat(::grpc::ServerContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftRPC::Service::OnRequestVote(::grpc::ServerContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace raft

