// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft_rpc.proto
#ifndef GRPC_raft_5frpc_2eproto__INCLUDED
#define GRPC_raft_5frpc_2eproto__INCLUDED

#include "raft_rpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace raft {

class RaftRPC final {
 public:
  static constexpr char const* service_full_name() {
    return "raft.RaftRPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::raft::HeartBeatReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::HeartBeatReply>> AsyncOnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::HeartBeatReply>>(AsyncOnHeartBeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::HeartBeatReply>> PrepareAsyncOnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::HeartBeatReply>>(PrepareAsyncOnHeartBeatRaw(context, request, cq));
    }
    virtual ::grpc::Status OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::raft::VoteReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::VoteReply>> AsyncOnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::VoteReply>>(AsyncOnRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::VoteReply>> PrepareAsyncOnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raft::VoteReply>>(PrepareAsyncOnRequestVoteRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft::HeartBeatReply>* AsyncOnHeartBeatRaw(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft::HeartBeatReply>* PrepareAsyncOnHeartBeatRaw(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft::VoteReply>* AsyncOnRequestVoteRaw(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raft::VoteReply>* PrepareAsyncOnRequestVoteRaw(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::raft::HeartBeatReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>> AsyncOnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>>(AsyncOnHeartBeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>> PrepareAsyncOnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>>(PrepareAsyncOnHeartBeatRaw(context, request, cq));
    }
    ::grpc::Status OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::raft::VoteReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::VoteReply>> AsyncOnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::VoteReply>>(AsyncOnRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::VoteReply>> PrepareAsyncOnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raft::VoteReply>>(PrepareAsyncOnRequestVoteRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response, std::function<void(::grpc::Status)>) override;
      void OnHeartBeat(::grpc::ClientContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response, std::function<void(::grpc::Status)>) override;
      void OnRequestVote(::grpc::ClientContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>* AsyncOnHeartBeatRaw(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft::HeartBeatReply>* PrepareAsyncOnHeartBeatRaw(::grpc::ClientContext* context, const ::raft::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft::VoteReply>* AsyncOnRequestVoteRaw(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raft::VoteReply>* PrepareAsyncOnRequestVoteRaw(::grpc::ClientContext* context, const ::raft::VoteRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OnHeartBeat_;
    const ::grpc::internal::RpcMethod rpcmethod_OnRequestVote_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OnHeartBeat(::grpc::ServerContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response);
    virtual ::grpc::Status OnRequestVote(::grpc::ServerContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OnHeartBeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnHeartBeat() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OnHeartBeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeartBeat(::grpc::ServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnHeartBeat(::grpc::ServerContext* context, ::raft::HeartBeatRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft::HeartBeatReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnRequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnRequestVote() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_OnRequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnRequestVote(::grpc::ServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnRequestVote(::grpc::ServerContext* context, ::raft::VoteRequest* request, ::grpc::ServerAsyncResponseWriter< ::raft::VoteReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OnHeartBeat<WithAsyncMethod_OnRequestVote<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OnHeartBeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnHeartBeat() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::raft::HeartBeatRequest, ::raft::HeartBeatReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft::HeartBeatRequest* request, ::raft::HeartBeatReply* response) { return this->OnHeartBeat(context, request, response); }));}
    void SetMessageAllocatorFor_OnHeartBeat(
        ::grpc::MessageAllocator< ::raft::HeartBeatRequest, ::raft::HeartBeatReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft::HeartBeatRequest, ::raft::HeartBeatReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OnHeartBeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeartBeat(::grpc::ServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnHeartBeat(
      ::grpc::CallbackServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OnRequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnRequestVote() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::raft::VoteRequest, ::raft::VoteReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::raft::VoteRequest* request, ::raft::VoteReply* response) { return this->OnRequestVote(context, request, response); }));}
    void SetMessageAllocatorFor_OnRequestVote(
        ::grpc::MessageAllocator< ::raft::VoteRequest, ::raft::VoteReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::raft::VoteRequest, ::raft::VoteReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OnRequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnRequestVote(::grpc::ServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnRequestVote(
      ::grpc::CallbackServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_OnHeartBeat<WithCallbackMethod_OnRequestVote<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OnHeartBeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnHeartBeat() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OnHeartBeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeartBeat(::grpc::ServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnRequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnRequestVote() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_OnRequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnRequestVote(::grpc::ServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnHeartBeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnHeartBeat() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OnHeartBeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeartBeat(::grpc::ServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnHeartBeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnRequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnRequestVote() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_OnRequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnRequestVote(::grpc::ServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnRequestVote(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnHeartBeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnHeartBeat() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnHeartBeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_OnHeartBeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeartBeat(::grpc::ServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnHeartBeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnRequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnRequestVote() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnRequestVote(context, request, response); }));
    }
    ~WithRawCallbackMethod_OnRequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnRequestVote(::grpc::ServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnRequestVote(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnHeartBeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnHeartBeat() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft::HeartBeatRequest, ::raft::HeartBeatReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft::HeartBeatRequest, ::raft::HeartBeatReply>* streamer) {
                       return this->StreamedOnHeartBeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnHeartBeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnHeartBeat(::grpc::ServerContext* /*context*/, const ::raft::HeartBeatRequest* /*request*/, ::raft::HeartBeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnHeartBeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft::HeartBeatRequest,::raft::HeartBeatReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnRequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnRequestVote() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raft::VoteRequest, ::raft::VoteReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::raft::VoteRequest, ::raft::VoteReply>* streamer) {
                       return this->StreamedOnRequestVote(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnRequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnRequestVote(::grpc::ServerContext* /*context*/, const ::raft::VoteRequest* /*request*/, ::raft::VoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnRequestVote(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raft::VoteRequest,::raft::VoteReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OnHeartBeat<WithStreamedUnaryMethod_OnRequestVote<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OnHeartBeat<WithStreamedUnaryMethod_OnRequestVote<Service > > StreamedService;
};

}  // namespace raft


#endif  // GRPC_raft_5frpc_2eproto__INCLUDED
