// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raftRPC.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_raftRPC_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_raftRPC_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_raftRPC_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_raftRPC_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_raftRPC_2eproto;
namespace raft {
class Entry;
struct EntryDefaultTypeInternal;
extern EntryDefaultTypeInternal _Entry_default_instance_;
class HeartBeatReply;
struct HeartBeatReplyDefaultTypeInternal;
extern HeartBeatReplyDefaultTypeInternal _HeartBeatReply_default_instance_;
class HeartBeatRequest;
struct HeartBeatRequestDefaultTypeInternal;
extern HeartBeatRequestDefaultTypeInternal _HeartBeatRequest_default_instance_;
class VoteReply;
struct VoteReplyDefaultTypeInternal;
extern VoteReplyDefaultTypeInternal _VoteReply_default_instance_;
class VoteRequest;
struct VoteRequestDefaultTypeInternal;
extern VoteRequestDefaultTypeInternal _VoteRequest_default_instance_;
}  // namespace raft
PROTOBUF_NAMESPACE_OPEN
template<> ::raft::Entry* Arena::CreateMaybeMessage<::raft::Entry>(Arena*);
template<> ::raft::HeartBeatReply* Arena::CreateMaybeMessage<::raft::HeartBeatReply>(Arena*);
template<> ::raft::HeartBeatRequest* Arena::CreateMaybeMessage<::raft::HeartBeatRequest>(Arena*);
template<> ::raft::VoteReply* Arena::CreateMaybeMessage<::raft::VoteReply>(Arena*);
template<> ::raft::VoteRequest* Arena::CreateMaybeMessage<::raft::VoteRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raft {

// ===================================================================

class Entry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.Entry) */ {
 public:
  inline Entry() : Entry(nullptr) {}
  ~Entry() override;
  explicit PROTOBUF_CONSTEXPR Entry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Entry(const Entry& from);
  Entry(Entry&& from) noexcept
    : Entry() {
    *this = ::std::move(from);
  }

  inline Entry& operator=(const Entry& from) {
    CopyFrom(from);
    return *this;
  }
  inline Entry& operator=(Entry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Entry& default_instance() {
    return *internal_default_instance();
  }
  static inline const Entry* internal_default_instance() {
    return reinterpret_cast<const Entry*>(
               &_Entry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Entry& a, Entry& b) {
    a.Swap(&b);
  }
  inline void Swap(Entry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Entry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Entry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Entry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Entry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Entry& from) {
    Entry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Entry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.Entry";
  }
  protected:
  explicit Entry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCmdFieldNumber = 3,
    kIndexFieldNumber = 1,
    kTermFieldNumber = 2,
  };
  // string cmd = 3;
  void clear_cmd();
  const std::string& cmd() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cmd(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cmd();
  PROTOBUF_NODISCARD std::string* release_cmd();
  void set_allocated_cmd(std::string* cmd);
  private:
  const std::string& _internal_cmd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cmd(const std::string& value);
  std::string* _internal_mutable_cmd();
  public:

  // int32 index = 1;
  void clear_index();
  int32_t index() const;
  void set_index(int32_t value);
  private:
  int32_t _internal_index() const;
  void _internal_set_index(int32_t value);
  public:

  // int32 term = 2;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raft.Entry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cmd_;
    int32_t index_;
    int32_t term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftRPC_2eproto;
};
// -------------------------------------------------------------------

class HeartBeatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.HeartBeatRequest) */ {
 public:
  inline HeartBeatRequest() : HeartBeatRequest(nullptr) {}
  ~HeartBeatRequest() override;
  explicit PROTOBUF_CONSTEXPR HeartBeatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeatRequest(const HeartBeatRequest& from);
  HeartBeatRequest(HeartBeatRequest&& from) noexcept
    : HeartBeatRequest() {
    *this = ::std::move(from);
  }

  inline HeartBeatRequest& operator=(const HeartBeatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeatRequest& operator=(HeartBeatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeatRequest* internal_default_instance() {
    return reinterpret_cast<const HeartBeatRequest*>(
               &_HeartBeatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HeartBeatRequest& a, HeartBeatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartBeatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartBeatRequest& from) {
    HeartBeatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartBeatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.HeartBeatRequest";
  }
  protected:
  explicit HeartBeatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 6,
    kTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kPrevIndexFieldNumber = 3,
    kPrevTermFieldNumber = 4,
    kCommitedIndexFieldNumber = 5,
  };
  // repeated .raft.Entry entries = 6;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::raft::Entry* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::Entry >*
      mutable_entries();
  private:
  const ::raft::Entry& _internal_entries(int index) const;
  ::raft::Entry* _internal_add_entries();
  public:
  const ::raft::Entry& entries(int index) const;
  ::raft::Entry* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::Entry >&
      entries() const;

  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 leader_id = 2;
  void clear_leader_id();
  int32_t leader_id() const;
  void set_leader_id(int32_t value);
  private:
  int32_t _internal_leader_id() const;
  void _internal_set_leader_id(int32_t value);
  public:

  // int32 prev_index = 3;
  void clear_prev_index();
  int32_t prev_index() const;
  void set_prev_index(int32_t value);
  private:
  int32_t _internal_prev_index() const;
  void _internal_set_prev_index(int32_t value);
  public:

  // int32 prev_term = 4;
  void clear_prev_term();
  int32_t prev_term() const;
  void set_prev_term(int32_t value);
  private:
  int32_t _internal_prev_term() const;
  void _internal_set_prev_term(int32_t value);
  public:

  // int32 commited_index = 5;
  void clear_commited_index();
  int32_t commited_index() const;
  void set_commited_index(int32_t value);
  private:
  int32_t _internal_commited_index() const;
  void _internal_set_commited_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raft.HeartBeatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::Entry > entries_;
    int32_t term_;
    int32_t leader_id_;
    int32_t prev_index_;
    int32_t prev_term_;
    int32_t commited_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftRPC_2eproto;
};
// -------------------------------------------------------------------

class HeartBeatReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.HeartBeatReply) */ {
 public:
  inline HeartBeatReply() : HeartBeatReply(nullptr) {}
  ~HeartBeatReply() override;
  explicit PROTOBUF_CONSTEXPR HeartBeatReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeatReply(const HeartBeatReply& from);
  HeartBeatReply(HeartBeatReply&& from) noexcept
    : HeartBeatReply() {
    *this = ::std::move(from);
  }

  inline HeartBeatReply& operator=(const HeartBeatReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeatReply& operator=(HeartBeatReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeatReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeatReply* internal_default_instance() {
    return reinterpret_cast<const HeartBeatReply*>(
               &_HeartBeatReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HeartBeatReply& a, HeartBeatReply& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeatReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeatReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeatReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeatReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartBeatReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartBeatReply& from) {
    HeartBeatReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartBeatReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.HeartBeatReply";
  }
  protected:
  explicit HeartBeatReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kSuccessFieldNumber = 2,
    kNextIndexFieldNumber = 3,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 next_index = 3;
  void clear_next_index();
  int32_t next_index() const;
  void set_next_index(int32_t value);
  private:
  int32_t _internal_next_index() const;
  void _internal_set_next_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raft.HeartBeatReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    bool success_;
    int32_t next_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftRPC_2eproto;
};
// -------------------------------------------------------------------

class VoteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.VoteRequest) */ {
 public:
  inline VoteRequest() : VoteRequest(nullptr) {}
  ~VoteRequest() override;
  explicit PROTOBUF_CONSTEXPR VoteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoteRequest(const VoteRequest& from);
  VoteRequest(VoteRequest&& from) noexcept
    : VoteRequest() {
    *this = ::std::move(from);
  }

  inline VoteRequest& operator=(const VoteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoteRequest& operator=(VoteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VoteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoteRequest* internal_default_instance() {
    return reinterpret_cast<const VoteRequest*>(
               &_VoteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(VoteRequest& a, VoteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(VoteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VoteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VoteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VoteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VoteRequest& from) {
    VoteRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VoteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.VoteRequest";
  }
  protected:
  explicit VoteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kCandidateIdFieldNumber = 2,
    kLastLogIndexFieldNumber = 3,
    kLastLogTermFieldNumber = 4,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 candidate_id = 2;
  void clear_candidate_id();
  int32_t candidate_id() const;
  void set_candidate_id(int32_t value);
  private:
  int32_t _internal_candidate_id() const;
  void _internal_set_candidate_id(int32_t value);
  public:

  // int32 last_log_index = 3;
  void clear_last_log_index();
  int32_t last_log_index() const;
  void set_last_log_index(int32_t value);
  private:
  int32_t _internal_last_log_index() const;
  void _internal_set_last_log_index(int32_t value);
  public:

  // int32 last_log_term = 4;
  void clear_last_log_term();
  int32_t last_log_term() const;
  void set_last_log_term(int32_t value);
  private:
  int32_t _internal_last_log_term() const;
  void _internal_set_last_log_term(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raft.VoteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    int32_t candidate_id_;
    int32_t last_log_index_;
    int32_t last_log_term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftRPC_2eproto;
};
// -------------------------------------------------------------------

class VoteReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raft.VoteReply) */ {
 public:
  inline VoteReply() : VoteReply(nullptr) {}
  ~VoteReply() override;
  explicit PROTOBUF_CONSTEXPR VoteReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoteReply(const VoteReply& from);
  VoteReply(VoteReply&& from) noexcept
    : VoteReply() {
    *this = ::std::move(from);
  }

  inline VoteReply& operator=(const VoteReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoteReply& operator=(VoteReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VoteReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoteReply* internal_default_instance() {
    return reinterpret_cast<const VoteReply*>(
               &_VoteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(VoteReply& a, VoteReply& b) {
    a.Swap(&b);
  }
  inline void Swap(VoteReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoteReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VoteReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VoteReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VoteReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VoteReply& from) {
    VoteReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VoteReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raft.VoteReply";
  }
  protected:
  explicit VoteReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // bool vote_granted = 2;
  void clear_vote_granted();
  bool vote_granted() const;
  void set_vote_granted(bool value);
  private:
  bool _internal_vote_granted() const;
  void _internal_set_vote_granted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:raft.VoteReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    bool vote_granted_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftRPC_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Entry

// int32 index = 1;
inline void Entry::clear_index() {
  _impl_.index_ = 0;
}
inline int32_t Entry::_internal_index() const {
  return _impl_.index_;
}
inline int32_t Entry::index() const {
  // @@protoc_insertion_point(field_get:raft.Entry.index)
  return _internal_index();
}
inline void Entry::_internal_set_index(int32_t value) {
  
  _impl_.index_ = value;
}
inline void Entry::set_index(int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:raft.Entry.index)
}

// int32 term = 2;
inline void Entry::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t Entry::_internal_term() const {
  return _impl_.term_;
}
inline int32_t Entry::term() const {
  // @@protoc_insertion_point(field_get:raft.Entry.term)
  return _internal_term();
}
inline void Entry::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void Entry::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.Entry.term)
}

// string cmd = 3;
inline void Entry::clear_cmd() {
  _impl_.cmd_.ClearToEmpty();
}
inline const std::string& Entry::cmd() const {
  // @@protoc_insertion_point(field_get:raft.Entry.cmd)
  return _internal_cmd();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Entry::set_cmd(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cmd_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:raft.Entry.cmd)
}
inline std::string* Entry::mutable_cmd() {
  std::string* _s = _internal_mutable_cmd();
  // @@protoc_insertion_point(field_mutable:raft.Entry.cmd)
  return _s;
}
inline const std::string& Entry::_internal_cmd() const {
  return _impl_.cmd_.Get();
}
inline void Entry::_internal_set_cmd(const std::string& value) {
  
  _impl_.cmd_.Set(value, GetArenaForAllocation());
}
inline std::string* Entry::_internal_mutable_cmd() {
  
  return _impl_.cmd_.Mutable(GetArenaForAllocation());
}
inline std::string* Entry::release_cmd() {
  // @@protoc_insertion_point(field_release:raft.Entry.cmd)
  return _impl_.cmd_.Release();
}
inline void Entry::set_allocated_cmd(std::string* cmd) {
  if (cmd != nullptr) {
    
  } else {
    
  }
  _impl_.cmd_.SetAllocated(cmd, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cmd_.IsDefault()) {
    _impl_.cmd_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:raft.Entry.cmd)
}

// -------------------------------------------------------------------

// HeartBeatRequest

// int32 term = 1;
inline void HeartBeatRequest::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t HeartBeatRequest::_internal_term() const {
  return _impl_.term_;
}
inline int32_t HeartBeatRequest::term() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatRequest.term)
  return _internal_term();
}
inline void HeartBeatRequest::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void HeartBeatRequest::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatRequest.term)
}

// int32 leader_id = 2;
inline void HeartBeatRequest::clear_leader_id() {
  _impl_.leader_id_ = 0;
}
inline int32_t HeartBeatRequest::_internal_leader_id() const {
  return _impl_.leader_id_;
}
inline int32_t HeartBeatRequest::leader_id() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatRequest.leader_id)
  return _internal_leader_id();
}
inline void HeartBeatRequest::_internal_set_leader_id(int32_t value) {
  
  _impl_.leader_id_ = value;
}
inline void HeartBeatRequest::set_leader_id(int32_t value) {
  _internal_set_leader_id(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatRequest.leader_id)
}

// int32 prev_index = 3;
inline void HeartBeatRequest::clear_prev_index() {
  _impl_.prev_index_ = 0;
}
inline int32_t HeartBeatRequest::_internal_prev_index() const {
  return _impl_.prev_index_;
}
inline int32_t HeartBeatRequest::prev_index() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatRequest.prev_index)
  return _internal_prev_index();
}
inline void HeartBeatRequest::_internal_set_prev_index(int32_t value) {
  
  _impl_.prev_index_ = value;
}
inline void HeartBeatRequest::set_prev_index(int32_t value) {
  _internal_set_prev_index(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatRequest.prev_index)
}

// int32 prev_term = 4;
inline void HeartBeatRequest::clear_prev_term() {
  _impl_.prev_term_ = 0;
}
inline int32_t HeartBeatRequest::_internal_prev_term() const {
  return _impl_.prev_term_;
}
inline int32_t HeartBeatRequest::prev_term() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatRequest.prev_term)
  return _internal_prev_term();
}
inline void HeartBeatRequest::_internal_set_prev_term(int32_t value) {
  
  _impl_.prev_term_ = value;
}
inline void HeartBeatRequest::set_prev_term(int32_t value) {
  _internal_set_prev_term(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatRequest.prev_term)
}

// int32 commited_index = 5;
inline void HeartBeatRequest::clear_commited_index() {
  _impl_.commited_index_ = 0;
}
inline int32_t HeartBeatRequest::_internal_commited_index() const {
  return _impl_.commited_index_;
}
inline int32_t HeartBeatRequest::commited_index() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatRequest.commited_index)
  return _internal_commited_index();
}
inline void HeartBeatRequest::_internal_set_commited_index(int32_t value) {
  
  _impl_.commited_index_ = value;
}
inline void HeartBeatRequest::set_commited_index(int32_t value) {
  _internal_set_commited_index(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatRequest.commited_index)
}

// repeated .raft.Entry entries = 6;
inline int HeartBeatRequest::_internal_entries_size() const {
  return _impl_.entries_.size();
}
inline int HeartBeatRequest::entries_size() const {
  return _internal_entries_size();
}
inline void HeartBeatRequest::clear_entries() {
  _impl_.entries_.Clear();
}
inline ::raft::Entry* HeartBeatRequest::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raft.HeartBeatRequest.entries)
  return _impl_.entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::Entry >*
HeartBeatRequest::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:raft.HeartBeatRequest.entries)
  return &_impl_.entries_;
}
inline const ::raft::Entry& HeartBeatRequest::_internal_entries(int index) const {
  return _impl_.entries_.Get(index);
}
inline const ::raft::Entry& HeartBeatRequest::entries(int index) const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatRequest.entries)
  return _internal_entries(index);
}
inline ::raft::Entry* HeartBeatRequest::_internal_add_entries() {
  return _impl_.entries_.Add();
}
inline ::raft::Entry* HeartBeatRequest::add_entries() {
  ::raft::Entry* _add = _internal_add_entries();
  // @@protoc_insertion_point(field_add:raft.HeartBeatRequest.entries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raft::Entry >&
HeartBeatRequest::entries() const {
  // @@protoc_insertion_point(field_list:raft.HeartBeatRequest.entries)
  return _impl_.entries_;
}

// -------------------------------------------------------------------

// HeartBeatReply

// int32 term = 1;
inline void HeartBeatReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t HeartBeatReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t HeartBeatReply::term() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatReply.term)
  return _internal_term();
}
inline void HeartBeatReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void HeartBeatReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatReply.term)
}

// bool success = 2;
inline void HeartBeatReply::clear_success() {
  _impl_.success_ = false;
}
inline bool HeartBeatReply::_internal_success() const {
  return _impl_.success_;
}
inline bool HeartBeatReply::success() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatReply.success)
  return _internal_success();
}
inline void HeartBeatReply::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void HeartBeatReply::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatReply.success)
}

// int32 next_index = 3;
inline void HeartBeatReply::clear_next_index() {
  _impl_.next_index_ = 0;
}
inline int32_t HeartBeatReply::_internal_next_index() const {
  return _impl_.next_index_;
}
inline int32_t HeartBeatReply::next_index() const {
  // @@protoc_insertion_point(field_get:raft.HeartBeatReply.next_index)
  return _internal_next_index();
}
inline void HeartBeatReply::_internal_set_next_index(int32_t value) {
  
  _impl_.next_index_ = value;
}
inline void HeartBeatReply::set_next_index(int32_t value) {
  _internal_set_next_index(value);
  // @@protoc_insertion_point(field_set:raft.HeartBeatReply.next_index)
}

// -------------------------------------------------------------------

// VoteRequest

// int32 term = 1;
inline void VoteRequest::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t VoteRequest::_internal_term() const {
  return _impl_.term_;
}
inline int32_t VoteRequest::term() const {
  // @@protoc_insertion_point(field_get:raft.VoteRequest.term)
  return _internal_term();
}
inline void VoteRequest::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void VoteRequest::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.VoteRequest.term)
}

// int32 candidate_id = 2;
inline void VoteRequest::clear_candidate_id() {
  _impl_.candidate_id_ = 0;
}
inline int32_t VoteRequest::_internal_candidate_id() const {
  return _impl_.candidate_id_;
}
inline int32_t VoteRequest::candidate_id() const {
  // @@protoc_insertion_point(field_get:raft.VoteRequest.candidate_id)
  return _internal_candidate_id();
}
inline void VoteRequest::_internal_set_candidate_id(int32_t value) {
  
  _impl_.candidate_id_ = value;
}
inline void VoteRequest::set_candidate_id(int32_t value) {
  _internal_set_candidate_id(value);
  // @@protoc_insertion_point(field_set:raft.VoteRequest.candidate_id)
}

// int32 last_log_index = 3;
inline void VoteRequest::clear_last_log_index() {
  _impl_.last_log_index_ = 0;
}
inline int32_t VoteRequest::_internal_last_log_index() const {
  return _impl_.last_log_index_;
}
inline int32_t VoteRequest::last_log_index() const {
  // @@protoc_insertion_point(field_get:raft.VoteRequest.last_log_index)
  return _internal_last_log_index();
}
inline void VoteRequest::_internal_set_last_log_index(int32_t value) {
  
  _impl_.last_log_index_ = value;
}
inline void VoteRequest::set_last_log_index(int32_t value) {
  _internal_set_last_log_index(value);
  // @@protoc_insertion_point(field_set:raft.VoteRequest.last_log_index)
}

// int32 last_log_term = 4;
inline void VoteRequest::clear_last_log_term() {
  _impl_.last_log_term_ = 0;
}
inline int32_t VoteRequest::_internal_last_log_term() const {
  return _impl_.last_log_term_;
}
inline int32_t VoteRequest::last_log_term() const {
  // @@protoc_insertion_point(field_get:raft.VoteRequest.last_log_term)
  return _internal_last_log_term();
}
inline void VoteRequest::_internal_set_last_log_term(int32_t value) {
  
  _impl_.last_log_term_ = value;
}
inline void VoteRequest::set_last_log_term(int32_t value) {
  _internal_set_last_log_term(value);
  // @@protoc_insertion_point(field_set:raft.VoteRequest.last_log_term)
}

// -------------------------------------------------------------------

// VoteReply

// int32 term = 1;
inline void VoteReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t VoteReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t VoteReply::term() const {
  // @@protoc_insertion_point(field_get:raft.VoteReply.term)
  return _internal_term();
}
inline void VoteReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void VoteReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raft.VoteReply.term)
}

// bool vote_granted = 2;
inline void VoteReply::clear_vote_granted() {
  _impl_.vote_granted_ = false;
}
inline bool VoteReply::_internal_vote_granted() const {
  return _impl_.vote_granted_;
}
inline bool VoteReply::vote_granted() const {
  // @@protoc_insertion_point(field_get:raft.VoteReply.vote_granted)
  return _internal_vote_granted();
}
inline void VoteReply::_internal_set_vote_granted(bool value) {
  
  _impl_.vote_granted_ = value;
}
inline void VoteReply::set_vote_granted(bool value) {
  _internal_set_vote_granted(value);
  // @@protoc_insertion_point(field_set:raft.VoteReply.vote_granted)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_raftRPC_2eproto
