// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_rpc.proto
#ifndef GRPC_server_5frpc_2eproto__INCLUDED
#define GRPC_server_5frpc_2eproto__INCLUDED

#include "server_rpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ser {

class serverRPC final {
 public:
  static constexpr char const* service_full_name() {
    return "ser.serverRPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 是否为leader节点
    virtual ::grpc::Status isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::ser::isLeaderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::isLeaderResponse>> AsyncisLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::isLeaderResponse>>(AsyncisLeaderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::isLeaderResponse>> PrepareAsyncisLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::isLeaderResponse>>(PrepareAsyncisLeaderRaw(context, request, cq));
    }
    // 执行kv操作指令
    virtual ::grpc::Status execute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::ser::executeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::executeResponse>> Asyncexecute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::executeResponse>>(AsyncexecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::executeResponse>> PrepareAsyncexecute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ser::executeResponse>>(PrepareAsyncexecuteRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 是否为leader节点
      virtual void isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 执行kv操作指令
      virtual void execute(::grpc::ClientContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void execute(::grpc::ClientContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ser::isLeaderResponse>* AsyncisLeaderRaw(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ser::isLeaderResponse>* PrepareAsyncisLeaderRaw(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ser::executeResponse>* AsyncexecuteRaw(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ser::executeResponse>* PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::ser::isLeaderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>> AsyncisLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>>(AsyncisLeaderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>> PrepareAsyncisLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>>(PrepareAsyncisLeaderRaw(context, request, cq));
    }
    ::grpc::Status execute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::ser::executeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::executeResponse>> Asyncexecute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::executeResponse>>(AsyncexecuteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::executeResponse>> PrepareAsyncexecute(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ser::executeResponse>>(PrepareAsyncexecuteRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response, std::function<void(::grpc::Status)>) override;
      void isLeader(::grpc::ClientContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void execute(::grpc::ClientContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response, std::function<void(::grpc::Status)>) override;
      void execute(::grpc::ClientContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>* AsyncisLeaderRaw(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ser::isLeaderResponse>* PrepareAsyncisLeaderRaw(::grpc::ClientContext* context, const ::ser::isLeaderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ser::executeResponse>* AsyncexecuteRaw(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ser::executeResponse>* PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::ser::executeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_isLeader_;
    const ::grpc::internal::RpcMethod rpcmethod_execute_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 是否为leader节点
    virtual ::grpc::Status isLeader(::grpc::ServerContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response);
    // 执行kv操作指令
    virtual ::grpc::Status execute(::grpc::ServerContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_isLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_isLeader() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_isLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status isLeader(::grpc::ServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestisLeader(::grpc::ServerContext* context, ::ser::isLeaderRequest* request, ::grpc::ServerAsyncResponseWriter< ::ser::isLeaderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_execute() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestexecute(::grpc::ServerContext* context, ::ser::executeRequest* request, ::grpc::ServerAsyncResponseWriter< ::ser::executeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_isLeader<WithAsyncMethod_execute<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_isLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_isLeader() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ser::isLeaderRequest, ::ser::isLeaderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ser::isLeaderRequest* request, ::ser::isLeaderResponse* response) { return this->isLeader(context, request, response); }));}
    void SetMessageAllocatorFor_isLeader(
        ::grpc::MessageAllocator< ::ser::isLeaderRequest, ::ser::isLeaderResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ser::isLeaderRequest, ::ser::isLeaderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_isLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status isLeader(::grpc::ServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* isLeader(
      ::grpc::CallbackServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_execute() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ser::executeRequest, ::ser::executeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ser::executeRequest* request, ::ser::executeResponse* response) { return this->execute(context, request, response); }));}
    void SetMessageAllocatorFor_execute(
        ::grpc::MessageAllocator< ::ser::executeRequest, ::ser::executeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ser::executeRequest, ::ser::executeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* execute(
      ::grpc::CallbackServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_isLeader<WithCallbackMethod_execute<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_isLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_isLeader() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_isLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status isLeader(::grpc::ServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_execute() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_isLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_isLeader() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_isLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status isLeader(::grpc::ServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestisLeader(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_execute() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestexecute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_isLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_isLeader() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->isLeader(context, request, response); }));
    }
    ~WithRawCallbackMethod_isLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status isLeader(::grpc::ServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* isLeader(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_execute() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->execute(context, request, response); }));
    }
    ~WithRawCallbackMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status execute(::grpc::ServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* execute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_isLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_isLeader() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ser::isLeaderRequest, ::ser::isLeaderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ser::isLeaderRequest, ::ser::isLeaderResponse>* streamer) {
                       return this->StreamedisLeader(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_isLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status isLeader(::grpc::ServerContext* /*context*/, const ::ser::isLeaderRequest* /*request*/, ::ser::isLeaderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedisLeader(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ser::isLeaderRequest,::ser::isLeaderResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_execute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_execute() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ser::executeRequest, ::ser::executeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ser::executeRequest, ::ser::executeResponse>* streamer) {
                       return this->Streamedexecute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_execute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status execute(::grpc::ServerContext* /*context*/, const ::ser::executeRequest* /*request*/, ::ser::executeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedexecute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ser::executeRequest,::ser::executeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_isLeader<WithStreamedUnaryMethod_execute<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_isLeader<WithStreamedUnaryMethod_execute<Service > > StreamedService;
};

}  // namespace ser


#endif  // GRPC_server_5frpc_2eproto__INCLUDED
